export const env = {
  nodeEnv: process.env.NODE_ENV ?? "development",
  port: Number(process.env.API_PORT ?? process.env.PORT ?? 3000),
  logLevel: process.env.LOG_LEVEL ?? "info",
  databaseUrl: process.env.DATABASE_URL,
  redisUrl: process.env.REDIS_URL ?? "redis://localhost:6379",
  sentryDsn: process.env.SENTRY_DSN,
  jwtAccessSecret: process.env.JWT_ACCESS_SECRET,
  jwtAccessExpiresIn: process.env.JWT_ACCESS_EXPIRES_IN ?? "15m",
  cookieDomain: process.env.COOKIE_DOMAIN,
  refreshTokenTtlDays: Number(process.env.REFRESH_TOKEN_TTL_DAYS ?? 30),
  minioEndpoint: process.env.MINIO_ENDPOINT ?? "localhost",
  minioPort: Number(process.env.MINIO_PORT ?? 9000),
  minioRootUser: process.env.MINIO_ROOT_USER,
  minioRootPassword: process.env.MINIO_ROOT_PASSWORD,
  minioBucket: process.env.MINIO_BUCKET ?? "murcha",
  eskizBaseUrl: process.env.ESKIZ_BASE_URL ?? "https://notify.eskiz.uz/api",
  eskizEmail: process.env.ESKIZ_EMAIL,
  eskizPassword: process.env.ESKIZ_PASSWORD,
  eskizSmsFrom: process.env.ESKIZ_SMS_FROM ?? "4546",
  appWebUrl: process.env.APP_WEB_URL ?? "https://app.murcha.uz",
  appShopUrl: process.env.APP_SHOP_URL ?? "https://shop.murcha.uz",
  vapidPublicKey: process.env.VAPID_PUBLIC_KEY,
  vapidPrivateKey: process.env.VAPID_PRIVATE_KEY,
  vapidSubject: process.env.VAPID_SUBJECT ?? "mailto:support@murcha.uz",
};
